-- MySQL Script generated by MySQL Workbench
-- Sun Jul 24 13:09:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;
-- -----------------------------------------------------
-- Table `Company`
-- -----------------------------------------------------

DROP TABLE IF exists `Users`;
CREATE TABLE IF NOT EXISTS `Users` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `date_time` DATETIME NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;

DROP TABLE IF exists `Category`;
CREATE TABLE IF NOT EXISTS `Category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;

-- DROP TABLE IF exists `Favorites`;
-- CREATE TABLE IF NOT EXISTS `Favorites` (
--   `favorites_id` INT NOT NULL AUTO_INCREMENT,
--   `email` VARCHAR(45) NOT NULL,
--   `post_id` INT NOT NULL,
--   PRIMARY KEY (`favorites_id`),
--     FOREIGN KEY (`email`) REFERENCES `Users` (`email`),
-- 	FOREIGN KEY (`post_id`) REFERENCES `Posts` (`post_id`)
--     ON DELETE CASCADE
--     ON UPDATE CASCADE)
-- ENGINE = InnoDB;

DROP TABLE IF EXISTS `Posts` ;
CREATE TABLE IF NOT EXISTS `Posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `category` INT NOT NULL,
  `description` VARCHAR(80) NOT NULL,
  `asking_price` VARCHAR(45) NOT NULL,
  `image` VARCHAR(80) NOT NULL,
  `image_thumbnail` VARCHAR(80) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `approved` INT NOT NULL,
  PRIMARY KEY (`post_id`),
	FOREIGN KEY (`category`) REFERENCES `Category` (`category_id`),
	FOREIGN KEY (`email`) REFERENCES `Users` (`email`)
ON DELETE CASCADE
ON UPDATE CASCADE)
ENGINE = InnoDB;

-- to approve posts: approved value must be 1


DROP TABLE IF exists `Message_Inbox`;
CREATE TABLE IF NOT EXISTS `Message_Inbox` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `message_txt` VARCHAR(45) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `message_sender_info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`message_id`),
  FOREIGN KEY (`post_id`) REFERENCES `Posts`(`post_id`)
  ON DELETE CASCADE)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


